version: "3.9"

services:
  postgres:
    image: postgres:16-alpine
    container_name: daylog-postgres
    restart: unless-stopped
    ports:
      - "5433:5432"
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - daylog_postgres_data:/var/lib/postgresql/data

  daylog:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: daylog-app
    volumes:
      - .:/app   # 🔥 код с хоста
    working_dir: /app
    command: ["go", "run", "./cmd/app"]
    environment:
      CONFIG_PATH: /app/config/local.yaml
      DB_HOST: postgres
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
      TELEGRAM_TOKEN: ${TELEGRAM_TOKEN}
      LLM_API_KEY: ${LLM_API_KEY}
    ports:
      - "8080:8080"
    depends_on:
      - postgres

volumes:
  daylog_postgres_data: