version: "3.9"

services:
  postgres:
    image: postgres:16-alpine
    container_name: daylog-postgres
    restart: unless-stopped
    ports:
      - "5433:5432"
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - daylog_postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}"]
      interval: 5s
      timeout: 5s
      retries: 10

  daylog:
    build: .
    container_name: daylog-app
    restart: unless-stopped
    environment:
      CONFIG_PATH: /app/config/prod.yaml

      #override
      DB_HOST: postgres

      #env
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
      TELEGRAM_TOKEN: ${TELEGRAM_TOKEN}
      LLM_API_KEY: ${LLM_API_KEY}
    depends_on:
      postgres:
        condition: service_healthy

volumes:
  daylog_postgres_data: